cd deberta_v3_large_pl_5th_tascj0
python ../stacking.py
cd ..
cd deberta_v2_xlarge_pl_5th_tascj0
python ../stacking.py
cd ..
cd deberta_xlarge_pl_5th_tascj0
python ../stacking.py
cd ..
cd deberta_v2_xlarge_pl_5th
python ../stacking.py
cd ..
cd deberta_v3_large_pl_5th
python ../stacking.py
cd ..
