cd deberta_v3_large_pl_3rd_tascj0
python ../stacking.py
cd ..
cd deberta_v2_xlarge_pl_3rd_tascj0
python ../stacking.py
cd ..
cd deberta_large_pl_3rd_tascj0
python ../stacking.py
cd ..
cd deberta_xlarge_pl_3rd_tascj0
python ../stacking.py
cd ..
cd deberta_v2_xlarge_pl_3rd
python ../stacking.py
cd ..
cd deberta_v3_large_pl_3rd
python ../stacking.py
cd ..
